// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHN6gTW3MkRWn-PYZcPSXXukBIO9-bFY',
    appId: '1:286971668450:web:18783de6a97585a72bfbbb',
    messagingSenderId: '286971668450',
    projectId: 'mitmi-108c1',
    authDomain: 'mitmi-108c1.firebaseapp.com',
    storageBucket: 'mitmi-108c1.appspot.com',
    measurementId: 'G-7XPDJ06PZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBOuT1YcudtleYVLtJvbEUHJ9mHwwHtMY',
    appId: '1:286971668450:android:9024a7d25b67240d2bfbbb',
    messagingSenderId: '286971668450',
    projectId: 'mitmi-108c1',
    storageBucket: 'mitmi-108c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwlQIHW1_jduvCjt7cekLlVeME3ECHtik',
    appId: '1:286971668450:ios:919c203add5735e62bfbbb',
    messagingSenderId: '286971668450',
    projectId: 'mitmi-108c1',
    storageBucket: 'mitmi-108c1.appspot.com',
    iosClientId: '286971668450-6copefp3f3obtjh4p6epbon7gs3s4a31.apps.googleusercontent.com',
    iosBundleId: 'com.example.mitmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwlQIHW1_jduvCjt7cekLlVeME3ECHtik',
    appId: '1:286971668450:ios:919c203add5735e62bfbbb',
    messagingSenderId: '286971668450',
    projectId: 'mitmi-108c1',
    storageBucket: 'mitmi-108c1.appspot.com',
    iosClientId: '286971668450-6copefp3f3obtjh4p6epbon7gs3s4a31.apps.googleusercontent.com',
    iosBundleId: 'com.example.mitmi',
  );
}
